services:
  app:
    build:
      context: .
      target: production
    env_file:
      - .env
    networks:
      - traefik
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.app-capture-live.rule=Host(`${TRAEFIK_HOST}`)
      - traefik.http.routers.app-capture-live.entrypoints=web
    volumes:
      - sqlite_data:/var/www/html/database

  queue:
    build:
      context: .
      target: production
    env_file:
      - .env
    restart: unless-stopped
    command: [ "php", "/var/www/html/artisan", "queue:work", "--tries=3" ]
    stop_signal: SIGTERM # Set this for graceful shutdown if you're using fpm-apache or fpm-nginx
    healthcheck:
      # This is our native healthcheck script for the queue
      test: [ "CMD", "healthcheck-queue" ]
      start_period: 10s
    networks:
      - traefik
    volumes:
      - sqlite_data:/var/www/html/database

volumes:
  sqlite_data:

networks:
  traefik:
    external: true
